/*
 * rgb.c
 *
 *  Created on: May 21, 2023
 *      Author: xq123
 */
#include "main.h"
#include "dma.h"
#include "tim.h"
#include "usart.h"
#include "gpio.h"
#include "rgb.h"

uint32_t RGB_Buffer[RGB_BUFFER_LENGTH] = {
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  NONE_PULSE,NONE_PULSE,NONE_PULSE,NONE_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,
  ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE,ZERO_PULSE
};

lefl_color_rgb_t RGB_Colors[4]={{0,0,0},{0,0,0},{0,0,0},{0,0,0}};

void RGB_Set(uint8_t r,uint8_t g,uint8_t b,uint16_t index)
{
  for (uint8_t i = 0;i < 8;i++)
  {
    RGB_Buffer[304+index*24+i]      = (g << i) & (0x80)?ONE_PULSE:ZERO_PULSE;
    RGB_Buffer[304+index*24+i + 8]  = (r << i) & (0x80)?ONE_PULSE:ZERO_PULSE;
    RGB_Buffer[304+index*24+i + 16] = (b << i) & (0x80)?ONE_PULSE:ZERO_PULSE;
  }
}

void RGB_Flash()
{
    for (uint8_t i=1;i<127;i++)
    {
      RGB_Set(i,i,i,0);
      RGB_Set(i,i,i,1);
      RGB_Set(i,i,i,2);
      RGB_Set(i,i,i,3);
      HAL_Delay(2);
    }
    for (uint8_t i=128;i>3;i--)
    {
      RGB_Set(i,i,i,0);
      RGB_Set(i,i,i,1);
      RGB_Set(i,i,i,2);
      RGB_Set(i,i,i,3);
      HAL_Delay(2);
    }
    RGB_TurnOff();
}

void RGB_TurnOff()
{
	for (uint8_t i=0;i<LED_NUM;i++)
    {
        RGB_Set(0,0,0,i);
    }
}
